"""Create GuestList table

Revision ID: 4651c2b8596c
Revises: f83603d8ee95
Create Date: 2023-10-17 11:49:08.837070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4651c2b8596c'
down_revision = 'f83603d8ee95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_guest_list_guest_id_guests')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_guest_list_party_id_parties')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.drop_table('guest_list')
    # ### end Alembic commands ###
