"""add back GuestList model

Revision ID: da7b69e310c1
Revises: 4651c2b8596c
Create Date: 2023-10-18 12:16:04.098528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7b69e310c1'
down_revision = '4651c2b8596c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_guest_lists_guest_id_guests')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_guest_lists_party_id_parties')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guest_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('party_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='fk_guest_list_guest_id_guests'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name='fk_guest_list_party_id_parties'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guest_lists')
    # ### end Alembic commands ###
